services:
  envoy:
    image: amalnull/envoy_proxy:tagname
    network_mode: "host"
    # healthcheck:
    #   test: curl --fail http://localhost:8080 || exit 1
    #   interval: 60s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s
    # depends_on:
    #     backend_node:
    #       condition: service_healthy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  backend_node:
    build: .
    container_name: node-application
    restart: always
    command: 'nodemon server.js'
    network_mode: "host"
    # healthcheck:
    #   test: curl --fail http://localhost:8888 || exit 1
    #   interval: 60s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s
    volumes:
      - .:/code
      - /code/node_modules
#  front_node:
#      build: frontend
#      container_name: node-frontend-application
#      restart: always
#      command: 'npm run serve'
#      network_mode: "host"
      # depends_on:
      #   envoy:
      #     condition: service_healthy
#      volumes:
#        - ./frontend:/project
#        - /project/node_modules
  redis:
      image: redis:alpine
      restart: always
      network_mode: "host"


  
